### ISSUE TITLE
Safe Mode problem

### ISSUE THREAD

**Issue by Elsewhereman** [Quicksaver/Puzzle-Toolbars#37]
I use Puzzle Piece in the hidden mode, positioned bottom right. Also using Classic Theme Restorer.

At some point - not sure when, but probably in one of the last couple of updates - a bug has been introduced which affects TPP when restarting after putting Firefox into Safe Mode. This removes all icons from the addon bar and puts them back into whatever we're supposed to call the button tray these days.

**Comment by Quicksaver** [comment]
Firefox 35 has been released, so this shouldn't happen anymore. Please open a new issue if it ever happens again.
