### ISSUE TITLE
Statusbar Not Movable

### ISSUE THREAD

**Issue by Techy-Ben** [Quicksaver/Puzzle-Toolbars#47]
When using The Puzzle Piece (TPP), I found that the statusbar is no longer movable.  However, I found an easy fix, which I would like to share here so you might consider including it on your next update.  In case you don't have time to read what happened and need to skip to the fix, the problem and failed workarounds are in the next paragraph and the fix is in the second to last paragraph.

I use a Firefox add-on (Auto Timer) that only works in the statusbar (I've tried to change the add-on to use toolbar buttons but I haven't figured it out), but I don't really use the statusbar for anything else.  So, I've moved my statusbar to CTR's "Additional Toolbar" and removed all the other buttons in it besides Auto Timer using another add-on [Organize Status Bar (Revived)] so that it sits below yet another add-on (a clock) and looks nice.  Well, I have a lot of other add-ons that have buttons I would like to access but hide, which is why I downloaded your "The Puzzle Piece" add-on.  Unfortunately, your add-on "hoarded" the statusbar, meaning the statusbar moved to the Puzzle Piece bar and I couldn't remove it.  This was a problem, because I wanted Auto Timer to be on the "Additional Toolbar" for appearance's sake and the only way to do that would be to move the statusbar.  I tried everything, including disabling TPP's behavior "Restore the status bar," using UIFixer, going into about:config, and downloading another add-on bar to take the statusbar away from TPP.  The only thing that partially worked was the last workaround, but the fix was not persistent by any means.  In order to fix the problem, I edited some of the code in TPP in order for it to work correctly.

Here's what I did: I went to chrome/content/australisBar.xul, found "<toolbaritem id="objName-status-bar-container"," and changed 'removable="false"' to true.  I then re-enabled TPP's behavior "Restore the status bar," and disabled CTR's behavior "Movable status-bar panel."  (I don't know if that was necessary, but at least it's not redundant now.)  I also removed the other add-on bar add-ons I tried, as well as UIFixer.  (I again, I don't know if that part was necessary, but I don't need them anymore.)

As a side note, any help making Auto Timer compatible with future versions of Firefox and moving it out of the statusbar would be welcome. ;)  Just a (rather impractical) thought, lol.

**Comment by Techy-Ben** [comment]
It works great, thanks! I'm sorry for not responding for so long...I haven't logged onto Github for quite a while.

**Comment by Quicksaver** [comment]
No problem, thanks for letting me know. :)
