### ISSUE TITLE
Losing all add-on icons in Puzzle Toolbars on reboot

### ISSUE THREAD

**Issue by paulderdash** [Quicksaver/Puzzle-Toolbars#58]
Using 2b9.
May be my particular configuration, but occasionally I am losing all my icons in the (bottom right corner) toolbar on rebooting. I have to repopulate using Customize. I haven't been able to detect a pattern here e.g. not closing browser before rebooting, so I am not able to point you to where the problem potentially lies! Could be another add-on that is causing this. Doesn't happen all the time, only sometimes.

**Comment by Quicksaver** [comment]
Firefox 35 has been released, so this shouldn't happen anymore. Please open a new issue (or re-open this one) if it ever happens again.

**Comment by paulderdash** [comment]
Hi Luiz

I know this is a long time ago ... I removed "CustomizableUI Debugger"
add-on, but I still have 'Debug' option against some extensions. Could it
be due to this add-on, and/or do you know how to remove that option?

I see devtools.chrome.enabled is set to true. Should I set this to false?

Best regards - Paul

**Comment by Quicksaver** [comment]
That debug button is from the add-ons manager itself, it will exist on every listed restartless extension that you have, as long as you have the the respective add-on debugging preference enabled. CUIDebugger should have disabled those when you removed it, but it's possible something might have gone wrong and it may have forgotten to do so.

Please try going to about:config and switching to false the following preferences:
browser.uiCustomization.debug
devtools.chrome.enabled
devtools.debugger.remote-enabled

**Comment by paulderdash** [comment]
That did it! Thanks Luis.

Paul

**Comment by Quicksaver** [comment]
No problem. :)
