### ISSUE TITLE
WOT (Web of Trust) icon refuses to stay on location toolbar

### ISSUE THREAD

**Issue by Jon-Best** [Quicksaver/Puzzle-Toolbars#78]
I don't know if there is anything you can do to fix this or if it's simply an issue with the WOT add-on itself, but when I move the icon to the location toolbar, it moves back to its original location as soon as I close Customize.

Addon homepage:
https://addons.mozilla.org/en-US/firefox/addon/wot-safe-browsing-tool/

**Comment by Quicksaver** [comment]
I assume you mean the button that shows the ratings panel and stuff (it's the only button that WOT installs for me at least).

The button works fine for me, it stays in the location bar toolbar or in any other toolbar I move it to, and it remains there after restarting firefox even. That seems like an old bug though, what version of Firefox and Puzzle Toolbars are you using? Could you try the latest version 2.0.8 of the add-on which hasn't been reviewed yet (https://addons.mozilla.org/en-US/firefox/addon/puzzle-toolbars/versions/) and see if it helps at all?

**Comment by Quicksaver** [comment]
Ah, go to WOT's preferences, show Advanced Settings, and disable "Re-create the toolbar button if it gets removed". ;)
