### ISSUE TITLE
Bug when used with Bookmark Toolbar

### ISSUE THREAD

**Issue by the-nothingman** [Quicksaver/Puzzle-Toolbars#80]
I'm experiencing a slight issue when I use the extension, If the bookmarks toolbar is moved to any of the Puzzle Bars then when the browser is opened then closed (or restarted) the Bookmark Toolbar will not show up until the Puzzle bar is closed then opened with a puzzle piece (or if the customize menu is opened) 

I'm not sure if this is an issue with the extension or how Firefox handles the Bookmark toolbar but it only happens with toolbars made by Puzzle

**Comment by Quicksaver** [comment]
You're right of course, thanks for letting me know. Could you try beta version 2.1b1 (https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1b1) and see if it fixes the issue for you please?

**Comment by the-nothingman** [comment]
fixes the issue perfectly
