### ISSUE TITLE
icon cannot correctly display

### ISSUE THREAD

**Issue by seventhsky** [Quicksaver/Puzzle-Toolbars#82]
![2](https://cloud.githubusercontent.com/assets/12661302/10035553/16c4b79c-61ce-11e5-9e3c-6eeb931cebf6.png)

Firefox 42.0b1

**Comment by Quicksaver** [comment]
Thanks for telling me about this. Could you please try beta version 2.1.4b1 (https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.4b1) and let me know how it works for you? At least the Hello! icon should be fixed, but if the others aren't I'll need to know where they come from.

**Comment by seventhsky** [comment]
![4](https://cloud.githubusercontent.com/assets/12661302/10042887/1d735294-6221-11e5-8888-11e7f041b77d.png)

It looks better now. Thank you!

**Comment by Quicksaver** [comment]
Great, let me know if you run into any other problems.
