### ISSUE TITLE
Options broken on Nightly (48.0a1 216-03-24)

### ISSUE THREAD

**Issue by the-nothingman** [Quicksaver/Puzzle-Toolbars#87]
Not sure when this broken originally but I just noticed when you try to open options for Puzzle Toolbar it opens a blank page marked "about:puzzlebars" with no way to change settings for the addon.

Doing a quick check all of your extensions that I use are similarly broken (Puzzle Bars, OmniSidebar, FindBar Tweak and Beyond Australis)

**Comment by Quicksaver** [comment]
Already fixed, will update soon. :) #86
