### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by davidhedlund** [Quicksaver/Puzzle-Toolbars#89]
There are no Mozilla License Headers (see https://www.mozilla.org/en-US/MPL/headers/) in your source files. Can you please add them?

**Comment by Quicksaver** [comment]
Those license headers are only required for files uploaded to Mozilla repos. The add-on already includes the full license at the root of the package, which extends to all files within it. The headers are not necessary as I understand it.

**Comment by davidhedlund** [comment]
Sorry, I didn't told you my purpose with this issue.

You need to add finish this issue so this page can be approved: https://directory.fsf.org/wiki/Puzzle_Toolbar

The Free Software Directory guidelines require license headers. Only when you have added them your entry can be approved by a moderator like me.

Can you please do this?

**Comment by Quicksaver** [comment]
I don't understand why that would be necessary. If you're distributing the add-on in the website, as long as its current licensing info is kept (the "LICENSE" file at the root), that should be enough. If you're not distributing it, then it shouldn't make a difference.

I don't want to add more licensing info than is absolutely necessary, and I don't know this website. Why is this necessary and what does it do for the add-on?

**Comment by davidhedlund** [comment]
License headers are absolutely necessary (see https://www.gnu.org/licenses/gpl-howto.en.html for example of GPL).

https://directory.fsf.org/wiki/Puzzle_Toolbar will automatically be listed for the latest GNU IceCat add-on repository (see https://directory.fsf.org/wiki/Free_Software_Directory:IceCat_extensions_(proposed) once done.

**Comment by Quicksaver** [comment]
My only issues are I don't want to spend a whole day attaching headers to over 1k files (I don't have just this add-on and I prefer consistency over anything else), and I'm against it myself because license headers only increase the file sizes to add info that, in this case, is redundant because the licensing is obvious from the single file included in the package and from the info in the add-on's homepage.

But if you want, you're welcome to submit a PR with the headers yourself. ;)

BTW it is already listed at https://directory.fsf.org/wiki/IceCat/Puzzle_Toolbars, although the name and version are severely outdated.

**Comment by davidhedlund** [comment]
What is the current name of the add-on then?

**Comment by Quicksaver** [comment]
Puzzle Bars: https://addons.mozilla.org/firefox/addon/puzzle-toolbars/

**Comment by davidhedlund** [comment]
The URL indicates the old name though. It would be less confusing if you changed it to https://addons.mozilla.org/firefox/addon/puzzle-bars/

**Comment by Quicksaver** [comment]
Changing urls doesn't redirect from the old to the new ones. So bookmarks would be lost, and users using older versions of the add-on (with the old urls) wouldn't be able to reach the right place. I avoid changing urls whenever possible.

**Comment by yfdyh000** [comment]
Why "urls doesn't redirect from the old to the new ones."? https://help.github.com/articles/renaming-a-repository/

**Comment by Quicksaver** [comment]
For instance, if I changed to https://github.com/Quicksaver/Puzzle-Bars, the current https://github.com/Quicksaver/Puzzle-Toolbars would no longer work.

**Comment by davidhedlund** [comment]
This is a separate issue.

**Comment by davidhedlund** [comment]
https://github.com/Quicksaver/Puzzle-Toolbars/issues/90

**Comment by davidhedlund** [comment]
label:license

**Comment by davidhedlund** [comment]
mylabel:license

**Comment by davidhedlund** [comment]
[mylabel:license](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Alicense%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by Quicksaver** [comment]
I'm sorry this took so long.

**Comment by davidhedlund** [comment]
No worries, you did it a last.

**Comment by davidhedlund** [comment]
[mylabel:re-evaluate](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Are-evaluate%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
> Releasing new versions on Addons.Mozilla.Org with the updated files with 
  > the headers is another matter. I have several more things to add and 
  > bugs to fix to the add-ons, so that will definitely take a while. But if 
  > you like I can still notify you when I update those as well.

Richard responded

> Please reply when that happens.
> 
> This is a long-term issue, not a super hurry.


Can you please re-open this issue until then?

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Apen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by Quicksaver** [comment]
Sure.

**Comment by davidhedlund** [comment]
@Quicksaver Thank you.

**Comment by davidhedlund** [comment]
[mylabel:AMO](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3AAMO%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by Quicksaver** [comment]
@davidhedlund replied to the e-mail as well. Done. :)

**Comment by davidhedlund** [comment]
@Quicksaver Thanks.

**Comment by davidhedlund** [comment]
Previously I recommended a modification of the GPL guidelines which was wrong. Now I've had a fresh look on the actual license.

From https://www.mozilla.org/en-US/MPL/2.0/

> If it is not possible or **desirable** to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

With other words, you can choose to use LICENSE, but no license notices in the source files.
