### ISSUE TITLE
Old title in URLs

### ISSUE THREAD

**Issue by davidhedlund** [Quicksaver/Puzzle-Toolbars#90]
Why are these URLs used instead:

* https://addons.mozilla.org/firefox/addon/puzzle-bars/
* https://github.com/Quicksaver/Puzzle-Bars

**Comment by Quicksaver** [comment]
I replied in #89.
> Changing urls doesn't redirect from the old to the new ones. So bookmarks would be lost, and users using older versions of the add-on (with the old urls) wouldn't be able to reach the right place. I avoid changing urls whenever possible.

**Comment by davidhedlund** [comment]
To rename GitHub repo as pointed out by @yfdyh000: https://help.github.com/articles/renaming-a-repository/

**Comment by Quicksaver** [comment]
> For instance, if I changed to https://github.com/Quicksaver/Puzzle-Bars, the current https://github.com/Quicksaver/Puzzle-Toolbars would no longer work.

**Comment by davidhedlund** [comment]
You could start https://github.com/Quicksaver/Puzzle-Bars and move the text from https://github.com/Quicksaver/Puzzle-Toolbars to it. And then state on https://github.com/Quicksaver/Puzzle-Toolbars that it have been moved to https://github.com/Quicksaver/Puzzle-Bars

**Comment by Quicksaver** [comment]
It doesn't work that way, that would require a complete new repository. It's definitely doable, but more work than it's worth.

**Comment by davidhedlund** [comment]
I think AMO lack resources its users then.

**Comment by Quicksaver** [comment]
I don't understand what you mean by that, but in AMO's case it wouldn't be possible at all to do something like this.

**Comment by davidhedlund** [comment]
They could offer redirects.

**Comment by Quicksaver** [comment]
Yeah but that's not up to me. ;)

**Comment by davidhedlund** [comment]
That is what I meant. However, we could petite for this if posted about this issue.

**Comment by davidhedlund** [comment]
I moved https://directory.fsf.org/wiki/IceCat/Puzzle_Toolbars to https://directory.fsf.org/wiki/IceCat/Puzzle_Bars and updated the version.
