### ISSUE TITLE
In the location bar, buttons with `badged-button` class don't match other buttons

### ISSUE THREAD

**Issue by blackwind** [Quicksaver/Puzzle-Toolbars#93]
As noted in the title, buttons with the `badged-button` class don't match the styling of other buttons in the location bar toolbar. One such add-on that uses this class is [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/). When placed in the location bar toolbar, its button appears to retain the standard toolbarbutton style, even when "Show the number of blocked requests on the icon" is disabled in uBO's settings.

The correct way to handle this would probably be for the offending add-on to remove the class when no longer used, but this isn't a practical solution for me as a user of Puzzle Toolbars, as uBlock isn't the only add-on I use that does this. As such, I'd love to see a fix on your end.

**Comment by Quicksaver** [comment]
I'll take a look, thanks for letting me know.

**Comment by Quicksaver** [comment]
It seems to look ok to me, can you send me a screenshot of how it looks to you? What operating system are you on?

**Comment by Quicksaver** [comment]
Also please try [beta version 2.1.15b1](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b1) and let me know if it makes any difference.

**Comment by blackwind** [comment]
With `badged-button` class:

![with](https://cloud.githubusercontent.com/assets/889881/19608779/8af46c7c-9790-11e6-8017-c12413757b98.png)

Without:

![without](https://cloud.githubusercontent.com/assets/889881/19608785/9147f0bc-9790-11e6-9878-676844c6f958.png)

Running Windows 10 with [this theme](http://virtualcustoms.net/showthread.php/72255-Windows-10-Black-Edition-for-Windows-10-Anniversary-Update-aka-Redstone-One) and the default Firefox theme. The beta didn't help.

**Comment by Quicksaver** [comment]
Hmm, are you sure it's the default Firefox theme? Does it also appear like that if you disable all other add-ons except for Puzzle Bars, and of course uBlock Origin?

I ask because the add-on doesn't really style the buttons based on any themes at all, it should just style the buttons all the same regardless.

**Comment by blackwind** [comment]
> Hmm, are you sure it's the default Firefox theme?

100% sure.

> Does it also appear like that if you disable all other add-ons except for Puzzle Bars, and of course uBlock Origin?

I just tested in a fresh profile with only those two add-ons, and I'm still able to reproduce.

> I ask because the add-on doesn't really style the buttons based on any themes at all, it should just style the buttons all the same regardless.

It should, but it seems to be ignoring buttons with that particular class. Or the rules for that class are overriding your rules.

**Comment by Quicksaver** [comment]
Alright I think I figured it out. Please try [beta version 2.1.15b2](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b2) and let me know how it looks for you.

**Comment by blackwind** [comment]
Only difference appears to be that you've changed the styling to match the corner toolbar. Buttons with the `badged-button` class still show the standard toolbar styling on top of your styling -- it's just slightly less noticeable this way until you click them. This new styling also makes my HTTPS Everywhere button look weird due to their silly toolbarbutton-within-a-toolbarbutton approach.

**Comment by Quicksaver** [comment]
Made some tweaks to [beta version 2.1.15b3](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b3), both badge buttons and the HTTPS Everywhere button should look better now.

**Comment by blackwind** [comment]
Perfect. Great work!

If I could make a suggestion for your next task, with Fx50 hitting the stable channel soon, Quicksaver/FindBar-Tweak#263 should be a top priority.
