### ISSUE TITLE
[Tab Groups \ hotkey interference] auto-hide makes the quick panel glitch

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Puzzle-Toolbars#97]
Quicksaver/Tab-Groups#446

**Comment by Quicksaver** [comment]
Please try [beta version 2.1.15b1](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b1) and let me know how it works for you.

**Comment by jmain33** [comment]
Thanks for looking into this. Using the beta, it now <ins>doesn't</ins> display the quick panel by way of the keyboard shortcut, until pressing it a second time that is.

  • so, no visual blip w/ PB–2.1.15b1; but the panel doesn't respond on first the call

`Win7 Pro 64-bit`, `Firefox 47.0.1`, `Puzzle Bars 2.1.15b1`

**Comment by Quicksaver** [comment]
Good catch, should work fine now on [beta version 2.1.15b2](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b2).

**Comment by jmain33** [comment]
:ok: Working well now; thanks for your effort and accolades for your skill.

**Comment by jmain33** [comment]
Sorry to say this has appeared again, this time Beyond Australis' "slim chrome" feature is the culprit.  I have the Tab Groups icon in the "Location Puzzle Bar" as usual >> calling upon it by use of the keyboard shortcut makes it pop into view for a split second and go away before once again establishing itself.  Sometimes it shows up on the left end, because of the mini location bar I'd presume, before positioning itself in the proper location (_this last scenario is extremely rare and most likely just a case of lagginess in the Firefox interface_).

Thought I'd post this here seeing as it's the same problem just has a new reason for raring its head; I know I'm a nag :stuck_out_tongue_closed_eyes:
